import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { Person, Prisma } from '@prisma/client';


//Prisma.XCreateInput = it exclude the autogeneratedd fields, it has the needed to create a new person
//User = It has the person record as it exists in the db (with autogenerated such as id)

@Injectable()
export class PersonService {
    constructor(private prisma: PrismaService) {}

    async createPerson(data: Prisma.PersonCreateInput): Promise<Person | null> {
        return this.prisma.person.create({data});
    };

    async getUsers(): Promise<Person[]> {
        return this.prisma.person.findMany();
    }

    

}
